### ISSUE TITLE
Implement unfollow user route

### ISSUE THREAD

**Issue by codeHatcher** [codeHatcher/lightTribe#75] opened 2015-09-21 01:14 UTC
#71

**Comment by footnote** [comment] 2015-10-21 01:19
Server crashes when using this route

**Comment by codeHatcher** [comment] 2015-10-21 01:20
Can you take a screenshot along with the data that you are sending.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Tue, Oct 20, 2015 at 6:19 PM, codeHatcher/lightTribe
<reply@reply.github.com>
wrote:
Server crashes when using this route

—
Reply to this email directly or view it on GitHub
[https://github.com/codeHatcher/lightTribe/issues/75#issuecomment-149751719] .[https://github.com/notifications/beacon/AFHNVsI9jcXo7rZFbloz5Nm73KP6jqbTks5o9t-_gaJpZM4GAmv5.gif]

**Comment by avishaan** [comment] 2015-11-08 01:30
@ShadiFares a screenshot is needed in order for the backend team to diagnose the issue. I'm going to close this for now. There are test cases for this and the issue is pretty old and can't be replicated without more information.

**Closed** 2015-11-08 01:33 UTC
